const APP_KEY = "YOUR_TWITTER_APP_KEY_HERE";
const APP_SECRET = "YOUR_TWITTER_APP_SECRET_HERE";
const ACCESS_TOKEN = "YOUR_TWITTER_ACCESS_TOKEN_HERE";
const ACCESS_SECRET = "YOUR_TWITTER_ACCESS_SECRET_HERE";
const CLAUDE_API_KEY = "YOUR_CLAUDE_KEY_HERE";

const SECRETS = {
  APP_KEY,
  APP_SECRET,
  ACCESS_TOKEN,
  ACCESS_SECRET,
  CLAUDE_API_KEY,
};

module.exports = SECRETS;
